
- name: Configure Docker on Deploy server Instance
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      command: sudo apt update -y

    - name: Install Docker
      command: sudo apt install docker.io -y 

    - name: Start Docker Service
      command: systemctl start docker

    - name: Run the Bank application
      command: sudo docker run -itd -p 8085:8081 anjalibhat/finance-me-app:latest
